contact_links:
  - name: Ask a question
    url: https://github.com/nodejsfunc/split_file_by_separator/discussions/new
    about: Ask and discuss questions with other split_file_by_separator community members
